#pragma once

namespace Engine
{
	enum class MouseButtonCode : uint16_t
	{
		E_MOUSE_BUTTON_1 = 0,
		E_MOUSE_BUTTON_2 = 1,
		E_MOUSE_BUTTON_3 = 2,
		E_MOUSE_BUTTON_4 = 3,
		E_MOUSE_BUTTON_5 = 4,
		E_MOUSE_BUTTON_6 = 5,
		E_MOUSE_BUTTON_7 = 6,
		E_MOUSE_BUTTON_8 = 7,
		E_MOUSE_BUTTON_LAST = E_MOUSE_BUTTON_8,
		E_MOUSE_BUTTON_LEFT = E_MOUSE_BUTTON_1,
		E_MOUSE_BUTTON_RIGHT = E_MOUSE_BUTTON_2,
		E_MOUSE_BUTTON_MIDDLE = E_MOUSE_BUTTON_3,
	};
}

#define MOUSE_BUTTON_1 0
#define MOUSE_BUTTON_2 1
#define MOUSE_BUTTON_3 2
#define MOUSE_BUTTON_4 3
#define MOUSE_BUTTON_5 4
#define MOUSE_BUTTON_6 5
#define MOUSE_BUTTON_7 6
#define MOUSE_BUTTON_8 7
#define MOUSE_BUTTON_LAST MOUSE_BUTTON_8
#define MOUSE_BUTTON_LEFT MOUSE_BUTTON_1
#define MOUSE_BUTTON_RIGHT MOUSE_BUTTON_2
#define MOUSE_BUTTON_MIDDLE MOUSE_BUTTON_3